"""Strategy interfaces and versioned implementations."""

from china_quant_platform.strategies.base import (
    DriverDirection,
    Explanation,
    ExplanationDriver,
    RawSignal,
    RawSignalIntent,
    Strategy,
    StrategyCondition,
    StrategyContext,
    StrategyEvaluation,
    StrategyMetadata,
    WarmupSpec,
    evaluate_strategy,
)
from china_quant_platform.strategies.etf_rotation import (
    CostTurnoverScenario,
    EtfRotationConfig,
    EtfRotationScore,
    EtfRotationSelection,
    EtfRotationStrategy,
    EtfSignalFeatures,
    EtfUniverseMember,
    ResearchStatus,
    cost_turnover_sensitivity,
)

__all__ = [
    "DriverDirection",
    "Explanation",
    "ExplanationDriver",
    "RawSignal",
    "RawSignalIntent",
    "Strategy",
    "StrategyCondition",
    "StrategyContext",
    "StrategyEvaluation",
    "StrategyMetadata",
    "WarmupSpec",
    "CostTurnoverScenario",
    "EtfRotationConfig",
    "EtfRotationScore",
    "EtfRotationSelection",
    "EtfRotationStrategy",
    "EtfSignalFeatures",
    "EtfUniverseMember",
    "ResearchStatus",
    "cost_turnover_sensitivity",
    "evaluate_strategy",
]
