"""Strategy interfaces and versioned implementations."""

from china_quant_platform.strategies.a_share_trend import (
    AShareFactorSnapshot,
    AShareTrendConfig,
    AShareTrendScore,
    AShareTrendSelection,
    AShareTrendStrategy,
    AShareUniverseMember,
    BreakdownRow,
    ExitDecision,
    cross_sectional_percentile_ranks,
    summarize_group_returns,
)
from china_quant_platform.strategies.base import (
    DriverDirection,
    Explanation,
    ExplanationDriver,
    RawSignal,
    RawSignalIntent,
    Strategy,
    StrategyCondition,
    StrategyContext,
    StrategyEvaluation,
    StrategyMetadata,
    WarmupSpec,
    evaluate_strategy,
)
from china_quant_platform.strategies.etf_rotation import (
    CostTurnoverScenario,
    EtfRotationConfig,
    EtfRotationScore,
    EtfRotationSelection,
    EtfRotationStrategy,
    EtfSignalFeatures,
    EtfUniverseMember,
    ResearchStatus,
    cost_turnover_sensitivity,
)

__all__ = [
    "DriverDirection",
    "Explanation",
    "ExplanationDriver",
    "AShareFactorSnapshot",
    "AShareTrendConfig",
    "AShareTrendScore",
    "AShareTrendSelection",
    "AShareTrendStrategy",
    "AShareUniverseMember",
    "BreakdownRow",
    "ExitDecision",
    "RawSignal",
    "RawSignalIntent",
    "Strategy",
    "StrategyCondition",
    "StrategyContext",
    "StrategyEvaluation",
    "StrategyMetadata",
    "WarmupSpec",
    "cross_sectional_percentile_ranks",
    "CostTurnoverScenario",
    "EtfRotationConfig",
    "EtfRotationScore",
    "EtfRotationSelection",
    "EtfRotationStrategy",
    "EtfSignalFeatures",
    "EtfUniverseMember",
    "ResearchStatus",
    "cost_turnover_sensitivity",
    "evaluate_strategy",
    "summarize_group_returns",
]
