"""Event-driven backtest engine package."""

from china_quant_platform.backtest.core import (
    BacktestCancellationToken,
    BacktestClock,
    BacktestEngine,
    BacktestEvent,
    BacktestEventLoop,
    BacktestEventType,
    BacktestRunResult,
    DeterministicExecutionSimulator,
    ExecutionReport,
    ExecutionStatus,
    OrderIntent,
    TradingSession,
)
from china_quant_platform.backtest.execution import (
    CorporateActionImpact,
    CorporateActionProcessor,
    ExecutionCostBreakdown,
    FixedBpsSlippageModel,
    FixedLatencyModel,
    FixedSpreadModel,
    ParticipationRateLiquidityModel,
    PositionState,
    RuleBasedCostModel,
)

__all__ = [
    "BacktestCancellationToken",
    "BacktestClock",
    "BacktestEngine",
    "BacktestEvent",
    "BacktestEventLoop",
    "BacktestEventType",
    "BacktestRunResult",
    "CorporateActionImpact",
    "CorporateActionProcessor",
    "DeterministicExecutionSimulator",
    "ExecutionCostBreakdown",
    "ExecutionReport",
    "ExecutionStatus",
    "FixedBpsSlippageModel",
    "FixedLatencyModel",
    "FixedSpreadModel",
    "OrderIntent",
    "ParticipationRateLiquidityModel",
    "PositionState",
    "RuleBasedCostModel",
    "TradingSession",
]
